<a href="https://colab.research.google.com/github/kushagrasharma-13/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Numpy

In [ ]:
import numpy as np
import pandas as pd
from numpy import array as ar

In [ ]:
a = ar([1,2,3,4,'a',6])
print(type(a))
print(a[0]+a[3])
print(a[0:3])

<class 'numpy.ndarray'>
14
['1' '2' '3']


In [ ]:
b = ar([[1,2,3,4,6],[7,'a',9,1,2]])
print(b)
print(np.shape(b))
print(np.ndim(b))
print(b.size)
print(b.dtype)
print(b[0,1])

[['1' '2' '3' '4' '6']
 ['7' 'a' '9' '1' '2']]
(2, 5)
2
10
<U21
2


In [ ]:
z = a.copy()
y = a.view()
print(z)
print(y)
r = b.reshape(5,2)
print(r)

['1' '2' '3' '4' 'a' '6']
['1' '2' '3' '4' 'a' '6']
[['1' '2']
 ['3' '4']
 ['6' '7']
 ['a' '9']
 ['1' '2']]


In [ ]:
a1 = ar([[1,2,3],[4,5,6]])           
for x1 in a1:
  print(x1)
for x2 in a1:                                  
  for y1 in x2:
    print(y1)        

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
a2 = np.array([1,2,3,4])
a3 = np.array([5,6,7,8])
a4 = np.concatenate((a2,a3))
print(a4)
a5 = np.array_split(a4,4)
print('\n',a5)
print(a5[0],'\n', a5[1],'\n', a5[2],'\n', a5[3])

[1 2 3 4 5 6 7 8]

 [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[1 2] 
 [3 4] 
 [5 6] 
 [7 8]


In [ ]:
a6 = ar([1,4,2,3,3,4])       # find indexes where element 4 is present.
a7 = np.where(a6==3)
print(a7)
print(np.sort(a6))
a8 = [True,False,True,False,True,True]
a9 = a6[a8]
print(a9)

(array([3, 4]),)
[1 2 3 3 4 4]
[1 2 3 4]


In [ ]:
c = [1,2,3,4,5]
df = pd.DataFrame(c)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
d  = ['p','a',1,'d','a','s']
e = pd.Series(d)
print(e)
print(e.dtype)

0    p
1    a
2    1
3    d
4    a
5    s
dtype: object
object


In [ ]:
f = [['Kushagra',19],['Shivam','Eighteen'],['Prakhar',21]]
g = pd.DataFrame(f,columns=['Name','Age'])
print(g)

       Name       Age
0  Kushagra        19
1    Shivam  Eighteen
2   Prakhar        21


In [ ]:
h = {'Name':['Kushagra','Shivam','Chhatra','Prakhar'],'Age':[19,'Eighteen',18,21]}
i = pd.DataFrame(h)
print(i)

       Name       Age
0  Kushagra        19
1    Shivam  Eighteen
2   Chhatra        18
3   Prakhar        21


In [ ]:
array = ar([[1,1,1],[2,4,8],[3,9,27],[4,16,64],[5,25,125],[6,36,216],[7,49,343]])
index = ['First',2,'Third','Fourth',5,'Sixth','Seventh']
colums = ['Number','Squares','Cube']
df = pd.DataFrame(data=array,index=index,columns=colums)
print(df)

         Number  Squares  Cube
First         1        1     1
2             2        4     8
Third         3        9    27
Fourth        4       16    64
5             5       25   125
Sixth         6       36   216
Seventh       7       49   343
